### ISSUE TITLE
What should I use instead of defines related to thread management

### ISSUE THREAD

**Issue by obones** [pleriche/FastMM5#15]
In my evaluation of moving from FastMM4 to FastMM5, I have to replace a few group of options that I created in FastMM4Options.inc by calls to the appropriate methods.
While most of them were easy, I'm struggling a bit with those ones:

    {$define AssumeMultiThreaded}
    {$define NeverSleepOnThreadContention}
    {$define UseSwitchToThread}

Looking at the code, it seems they are simply now integrated by default and that there is nothing to activate when they are present, or deactivate should they be undefined.
Am I right?

**Comment by pleriche** [comment]
Hi Olivier,

You are correct: Those options are obsolete. The are all effectively always on in v5.

Best regards,
Pierre

**Comment by obones** [comment]
Thanks for the confirmation, this is fine by me.
