### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by stef-pellegrino** [pleriche/FastMM5#2]
With windows 10, Rio (10.3 update 1)

App is a VCL MDI...
Works with FastMM4 but crashes with FastMM5 when closing...
:(

**Comment by pleriche** [comment]
Hi Stephane, 

When you say it crashes, what exactly happens? What error message do you get? If an exception is raised, is it inside FastMM5.pas, or elsewhere?

Also have you tried enabling debug mode? Call FastMM_EnableDebugMode during application startup - perhaps that will help you narrow down the issue. Also, if you want to log memory leaks to file, you have to include memory leaks in the events that are logged to file, like this:
FastMM_LogToFileEvents := FastMM_LogToFileEvents + [mmetUnexpectedMemoryLeakDetail, mmetUnexpectedMemoryLeakSummary];

Best regards,
Pierre

**Comment by stef-pellegrino** [comment]
Hi Pierre,
With this option, it works, indeed... !
My mistake. And thanks again for the tool !

... And don't forget RTMFM :)
