### ISSUE TITLE
Medium blocs are never released even with FastMM_SetOptimizationStrategy (mmosOptimizeForLowMemoryUsage)

### ISSUE THREAD

**Issue by mterrisse** [pleriche/FastMM5#27]
Hello,

We have noticed that our server applications consume much memory and never release it to the system.
The system is running low virtual memory durably and ends up crashing.
In detail they get much memory from medium and large blocs and release them, but OS_FreeVirtualMemory is never called for medium blocs.
For medium blocs, OS_FreeVirtualMemory is called only at the end of the application in FastMM_FreeAllMemory. Just before we enter FastMM_FreeAllMemory the memory is very high, after FastMM_FreeAllMemory it is very low.
So we tried FastMM_SetOptimizationStrategy (mmosOptimizeForLowMemoryUsage), but it doesn't change anything.
If we set a breakpoint in FastMM_FreeMem_InternalFreeMediumBlock_ManagerAlreadyLocked where OS_FreeVirtualMemory is called, we notice that it is never called.
Did we miss something?
Is there anything else we should set than the optimization strategy?

Regards,

Michel Terrisse

**Comment by pleriche** [comment]
Hi Michel,

If FastMM is not releasing address space back the the OS, then the first thing I would check is whether it is not perhaps running in debug mode. What is the result of the FastMM_DebugModeActive call?

Pierre

**Comment by mterrisse** [comment]
Hello,

FastMM_DebugModeActive() returns False.

I am trying to build a sample project to help reproducing ithe problem. I will post it here when it is ready.
It seams to me that you don't need to have many threads to reproduce it, I have a mono-threaded application that keeps much memory until FastMM_FreeAllMemory.

Regards,

Michel Terrisse

**Comment by pleriche** [comment]
Do you see this behaviour with the default memory manager or FastMM4 as well? If not, that's quite odd.

A test case will be very helpful. If it is too big to post here you're welcome to e-mail it to me directly as well. Thanks.

**Comment by mterrisse** [comment]
Hello,

We have run many tests with one of our applications (a web server) and we have noticed this:
- We don't have this behaviour with the default memory manager.
- When we stop the application a few minutes after a massive use of memory, we come into FastMM_FreeAllMemory at the end of the application with a lot of extra memory allocated (up to more than 100MB), but nothing used by the application (checked with FastMM_GetHeapStatus), and everything is released by FastMM_FreeAllMemory.
- BUT if we don't stop the application and keep it running with a "normal" activity, after many hours (about 15 hours for a test yesterday), then the memory returns to what it was before the massive use of memory.

So even though we can't figure how it works, FastMM behaves as expected and there is no bug here.
You can close this ticket, sorry for the inconvenience.

Regards,

Michel Terrisse

**Comment by pleriche** [comment]
Thank you for the feedback. I'll close the ticket.
