### ISSUE TITLE
W1071 Implicit integer cast with potential data loss from 'Cardinal' to 'Integer'

### ISSUE THREAD

**Issue by AtlasHackert** [pleriche/FastMM5#33]
FastMM5.pas, line 7891:
`for i := 1 to AMaxDepth do`

AMaxDepth is a Cardinal, i is an Integer, resulting in a compiler warning. Since i is otherwise unused. I'd make i a Cardinal as well.

**Comment by pleriche** [comment]
Thank you for reporting this. I have fixed this warning and all the other W7071 errors.

**Comment by AtlasHackert** [comment]
Confirmed fixed! Thanks! :)
