### ISSUE TITLE
NoDebugInfo backwards compatibility option inverted?

### ISSUE THREAD

**Issue by AtlasHackert** [pleriche/FastMM5#34]
FastMM5.pas, line 176:
`{$ifdef NoDebugInfo} {$undef FastMM_NoDebugInfo} {$endif}`

That "$undef" seems inverted? Shouldn't that be a "$define"?

**Comment by pleriche** [comment]
You're right, thanks. It's fixed.

**Comment by AtlasHackert** [comment]
Awesome, thanks! :)
