### ISSUE TITLE
"Allocation Group" feature missing?

### ISSUE THREAD

**Issue by dcabale** [pleriche/FastMM5#36]
Hey there,
It seems that FastMM5 does not provide the (very useful) "Allocation Group" feature, present in FastMM4. Am I right ?
If I am, is that feature in the FastMM5 roadmap ?
If not, what do you currently propose for logging allocations by group ?
Thanks for your help.

**Comment by pleriche** [comment]
Hi,

It does have a global variable "FastMM_CurrentAllocationGroup" that gets stored in the header of debug blocks, but there's no filter in FastMM_WalkBlocks to filter by allocation group - that has to happen client side (at least currently).

Are you specifically after something like the LogAllocatedBlocksToFile call in FastMM4?

**Comment by dcabale** [comment]
Exactly, such a FastMM4 procedure `LogAllocatedBlocksToFile(AFirstAllocationGroupToLog, ALastAllocationGroupToLog: Cardinal)` that publish Allocation Groups to the user is missing.
And as you perfectly understood my need, function `FastMM_WalkBlocks(xxxx)` does not provide such a filter.
Thanks for your understanding

**Comment by pleriche** [comment]
Ok, I'll see what I can do.

**Comment by pleriche** [comment]
Please see the latest commit and confirm whether this addresses your request adequately.

**Comment by dcabale** [comment]
After a little test, it seems to satisfy my request -> Thanks a lot !
