### ISSUE TITLE
Change FastMM_LogStateToFile FileName parameter from const string into PChar

### ISSUE THREAD

**Issue by HHasenack** [pleriche/FastMM5#45]
It is currently defined as a `const string`, please change into simple `PChar`
Why?
Because when calling the routine, even when providing `PChar` parameter the routine, the compiler decides to allocate a string resulting in a memory report with an allocation leak that is actually the string allocated for the parameter.

I changed it in my FastMM.pas and appears to have no furthed adverse effects in compiling and running.

TIA Hans

**Comment by pleriche** [comment]
Done
