### ISSUE TITLE
FastMM Usage Tracker issue

### ISSUE THREAD

**Issue by myonlylonely** [pleriche/FastMM5#48]
Hey Pierre,
I copied FastMM Usage Tracker from FastMM4 to FastMM5, it compiled without any issue.
But when I open the Usage Tracker window, the first tab shows that almost all the usage number is zero. It did show the correct info when I switch back to FastMM4.
I know FastMM5 changed a lot, so is it possible for the Usage Tracker to work under FastMM5?

**Comment by pleriche** [comment]
Hi,

It is on the to-do list to update the usage tracker for FastMM5, but I can't commit to a a timeline for it at this stage.

Best regards,
Pierre

**Comment by myonlylonely** [comment]
Thanks for the info. Could you please explain the reason for the numbers showing zero?

**Comment by pleriche** [comment]
I have ported the usage tracker to FastMM5.

**Comment by myonlylonely** [comment]
Great! I have tested it without any issue.👍
